tomsgu_sylius_gift_admin_gift_option:
    resource: |
        alias: tomsgu_sylius_gift.gift_option
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: tomsgu_sylius_gift_gift_option
        vars:
            index:
                icon: 'tabler:gift'
    type: sylius.resource
